# Generated by Django 5.0.6 on 2026-04-29 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('budget_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('usage_inputs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('llm', 'LLM'), ('vector_db', 'Vector DB'), ('hosting', 'Hosting'), ('storage', 'Storage'), ('payments', 'Payments'), ('monitoring', 'Monitoring'), ('communication', 'Communication'), ('auth', 'Auth'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('is_official', models.BooleanField(default=False)),
                ('icon_color', models.CharField(default='#22d3ee', max_length=16)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Community Vote')], default='approved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
                ('model_type', models.CharField(choices=[('per_token', 'Per Token'), ('per_seat', 'Per Seat'), ('per_request', 'Per Request'), ('flat_rate', 'Flat Rate'), ('usage_based', 'Usage Based'), ('tiered', 'Tiered')], max_length=32)),
                ('usage_inputs', models.JSONField(default=dict)),
                ('is_official', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variants', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.service')),
            ],
            options={
                'ordering': ['-is_official', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_inputs', models.JSONField(blank=True, default=dict)),
                ('custom_model_type', models.CharField(blank=True, choices=[('per_token', 'Per Token'), ('per_seat', 'Per Seat'), ('per_request', 'Per Request'), ('flat_rate', 'Flat Rate'), ('usage_based', 'Usage Based'), ('tiered', 'Tiered')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='api.project')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pricingvariant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.service')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('project', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.pricingvariant')),
            ],
            options={
                'unique_together': {('variant', 'user')},
            },
        ),
    ]
