# Generated by Django 5.0.6 on 2026-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingvariant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
